theme: jekyll-theme-minimal
title: 'Psycomp Lab'
description: '<p style="text-align:left">Psycomp Lab, University of Rome, La Sapienza @ Computer Science Department & Psychology Department</p>'
logo: /imgs/logo.png
show_downloads: false
