theme: jekyll-theme-minimal
title: 'Psycomp Lab'
description: '<p style="text-align:left">Psycomp Lab @ Computer Science Department & Psychology Department, Sapienza University of Rome</p>'
logo: /imgs/logo.png
show_downloads: false
